CREATE TABLE IF NOT EXISTS VERSION (
  VER_ID INTEGER PRIMARY KEY,
  SCHEMA_VERSION VARCHAR(127) NOT NULL,
  VERSION_COMMENT VARCHAR(255)
);

INSERT INTO VERSION (VER_ID, SCHEMA_VERSION, VERSION_COMMENT) 
VALUES (1, '4.0.0', 'Initial Hive 4.0.0 schema');

CREATE TABLE IF NOT EXISTS DBS (
  DB_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(128) NOT NULL,
  DB_LOCATION_URI VARCHAR(1000) NOT NULL,
  OWNER_NAME VARCHAR(128),
  OWNER_TYPE VARCHAR(10),
  CTLGS_NAME VARCHAR(256) DEFAULT 'hive'
);
